### ISSUE TITLE
Work with pure functional components

### ISSUE THREAD

**Issue by vlabs** [schneckentempo/ClicksAndImpressions_v2#2]
https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components

for example here:
https://github.com/schneckentempo/ClicksAndImpressions_v2/blob/master/src/components/HeaderText.js

**Comment by schneckentempo** [comment]
Hallo Tom,
Ich hab ein neues Repo _v3 angelegt und diese Aufgabenstellung versucht zu lösen. Allerdings erhalte ich eine Fehlermeldung die sagt ich soll die render-Methode in der ImpressionsPage überprüfen. Woran scheiterts?

Lg
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.10.16, 09:52, Thomas Meindl <notifications@github.com> schrieb:

  
    
      https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components
    
    
      for example here:
      https://github.com/schneckentempo/ClicksAndImpressions_v2/blob/master/src/components/HeaderText.js

**Comment by vlabs** [comment]
bitte generell mit branches und pull requests arbeiten..
https://help.github.com/articles/about-pull-requests/

du musst die function noch exportieren..

**Comment by vlabs** [comment]
kannst du die arbeit bitte auf diesem repository fortführen!

**Comment by vlabs** [comment]
ausserdem: we should talk english :)

**Comment by schneckentempo** [comment]
Mit erhalt der Ordnerstruktur oder mit der von der neuen boilerplate? Sprich einfach package.json austauschen oder pull von v3 in v2?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.10.16, 13:45, Thomas Meindl <notifications@github.com> schrieb:

  
    
      kannst du die arbeit bitte auf diesem repository fortführen!

**Comment by vlabs** [comment]
i would
- forget v1,
- work with v2,
- kill v3,
- and apply changes from v3 into a PR on v2
